### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by horstoeko** [PrinsFrank/pdfparser#256]
Hi!

I would like to move away from smalot/pdfparser with my [horstoeko/zugferd](https://github.com/horstoeko/zugferd) library. Unfortunately, I have not yet found a way to read attachments attached to the PDF. Can you give me some advice on how to do this with your library?

I am currently using the following code with the help of smalot/pdfparser:

```php
$this->attachmentContentList = [];

$pdfParser = new PdfParser();
$pdfParsed = $pdfParser->parseContent($pdfContent);
$fileSpecs = $pdfParsed->getObjectsByType('Filespec');

$fileSpecs = array_filter(
    $fileSpecs,
    function ($fileSpec) {
        return $fileSpec->has('F') && $fileSpec->has('EF');
    }
);

$fileSpecs = array_filter(
    $fileSpecs,
    function ($fileSpec) {
        return $fileSpec->get('EF')->has('F');
    }
);

foreach ($fileSpecs as $fileSpec) {
    $this->attachmentContentList[] = [
        ZugferdDocumentPdfReaderExt::ATTACHMENT_KEY_TYPE => in_array($fileSpec->get('F')->getContent(), ZugferdDocumentPdfReaderExt::ATTACHMENT_FILENAMES) ? ZugferdDocumentPdfReaderExt::ATTACHMENT_TYPE_XMLINVOICE : ZugferdDocumentPdfReaderExt::ATTACHMENT_TYPE_ADDITIONAL,
        ZugferdDocumentPdfReaderExt::ATTACHMENT_KEY_CONTENT => $fileSpec->get('EF')->get('F')->getContent(),
        ZugferdDocumentPdfReaderExt::ATTACHMENT_KEY_FILENAME => $fileSpec->get('F')->getContent(),
        ZugferdDocumentPdfReaderExt::ATTACHMENT_KEY_MIMETYPE => $fileSpec->get('EF')->get('F')->has('Subtype') ? (string)($fileSpec->get('EF')->get('F')->get('Subtype')->getContent()) : "",
    ];
}
``` 

Is there a similar way to implement this with your library?

I would be delighted to hear from you in this regard.

Kind regards

**Comment by horstoeko** [comment]
Hi @PrinsFrank 

Thank you very much for your work so far. I can now indeed read in the PDFs. Unfortunately, I am still getting some ‘deprecated’ warnings. Furthermore, I am still not sure how to obtain the following information:

* File name of the attachment
* MimeType of the attachment
* The content of the attachment.

I have currently implemented the following:

```php
$this->attachmentContentList = [];

$pdfParser = new PdfParser();
$pdfParsed = $pdfParser->parseString($pdfContent);
$fileSpecs = $pdfParsed->getCatalog()->getFileSpecifications();

foreach ($fileSpecs as $fileSpec) {
    if (($embeddedFile = $fileSpec->getEmbeddedFile()) === null) {
        continue;
    }

    // What to do here??? 

    /*
    $this->attachmentContentList[] = [
        ZugferdDocumentPdfReaderExt::ATTACHMENT_KEY_TYPE => in_array($fileSpec->get('F')->getContent(), ZugferdDocumentPdfReaderExt::ATTACHMENT_FILENAMES) ? ZugferdDocumentPdfReaderExt::ATTACHMENT_TYPE_XMLINVOICE : ZugferdDocumentPdfReaderExt::ATTACHMENT_TYPE_ADDITIONAL,
        ZugferdDocumentPdfReaderExt::ATTACHMENT_KEY_CONTENT => $fileSpec->get('EF')->get('F')->getContent(),
        ZugferdDocumentPdfReaderExt::ATTACHMENT_KEY_FILENAME => $fileSpec->get('F')->getContent(),
        ZugferdDocumentPdfReaderExt::ATTACHMENT_KEY_MIMETYPE => $fileSpec->get('EF')->get('F')->has('Subtype') ? (string)($fileSpec->get('EF')->get('F')->get('Subtype')->getContent()) : "",
    ];
    */
}

return $this;
```

May you help me?

Kind regards

**Comment by PrinsFrank** [comment]
@horstoeko No problem! The deprecation issues should be fixed with the most recent release! I think this should be a direct replacement of what you currently are retrieving through the other methods:

```php
$this->attachmentContentList = [];

$pdfParser = new PdfParser();
$pdfParsed = $pdfParser->parseString($pdfContent);
$fileSpecs = $pdfParsed->getCatalog()->getFileSpecifications();

foreach ($fileSpecs as $fileSpec) {
    if (($embeddedFile = $fileSpec->getEmbeddedFile()) === null) {
        continue;
    }

    // What to do here??? 
    $this->attachmentContentList[] = [
        ZugferdDocumentPdfReaderExt::ATTACHMENT_KEY_TYPE => in_array($fileSpec->getFileSpecificationString(), ZugferdDocumentPdfReaderExt::ATTACHMENT_FILENAMES) ? ZugferdDocumentPdfReaderExt::ATTACHMENT_TYPE_XMLINVOICE : ZugferdDocumentPdfReaderExt::ATTACHMENT_TYPE_ADDITIONAL,
        ZugferdDocumentPdfReaderExt::ATTACHMENT_KEY_CONTENT => $fileSpec->getStream()->toString(), // You could pass along the stream object to not assign a bunch of memory for the string representation here
        ZugferdDocumentPdfReaderExt::ATTACHMENT_KEY_FILENAME => $fileSpec->getFileSpecificationString(),
        ZugferdDocumentPdfReaderExt::ATTACHMENT_KEY_MIMETYPE => ltrim($fileSpec->getEmbeddedFile()->getSubType() ?? '', '/'), // ltrim is necesarry here because the nameObject starts with a leading forward slash but that was not included before
    ];
}

return $this;
```

Hope this helps, let me know if I missed something or if I can help you with anything else!!

**Comment by horstoeko** [comment]
Hi @PrinsFrank 

Everything looks very good at the moment. However, I still have the problem that your library requires a PHP version >= 8.1, while my library requires >= 7.3. I still need to solve this problem, unless you have another idea... :-) Otherwise, there would be nothing standing in the way of using your library...

**Comment by PrinsFrank** [comment]
Good to hear! Sorry about the wrong method for the file contents, I wrote that a bit to quickly, I'm glad you managed to figure out the correct method!

Regarding minimum required PHP version: Most open source PHP libraries will only support versions that have either active support or security support. PHP8.1 is [currently the oldest version that still has security support](https://www.php.net/supported-versions.php), and even that is ending at the end of the year. The majority of popular packages has dropped support for 8.1 already, and I might do so as well at the start of next year.

Given the [download statistics of your package](https://packagist.org/packages/horstoeko/zugferd/php-stats) I'd say it's safe to update the minimum required version to 8.1. The latest data point shows 0.1% PHP7.3, 0.6% PHP7.4 and 0.2% PHP8.0. Running any older versions is dangerous at this point, especially for users of your package as it involves financial data!

**Comment by horstoeko** [comment]
Hi @PrinsFrank,

> Regarding minimum required PHP version: Most open source PHP libraries will only support versions that have either active support or security support. PHP8.1 is [currently the oldest version that still has security support](https://www.php.net/supported-versions.php), and even that is ending at the end of the year. The majority of popular packages has dropped support for 8.1 already, and I might do so as well at the start of next year.
 
> Given the [download statistics of your package](https://packagist.org/packages/horstoeko/zugferd/php-stats) I'd say it's safe to update the minimum required version to 8.1. The latest data point shows 0.1% PHP7.3, 0.6% PHP7.4 and 0.2% PHP8.0. Running any older versions is dangerous at this point, especially for users of your package as it involves financial data!

What you write is absolutely correct. I will consider using PHP 8.1 as a minimum requirement.

Thank you again for your commitment and your good work.

Kind regards
